### ISSUE TITLE
ItemEnchantedBook/ScreenConfigureGlasses crash

### ISSUE THREAD

**Issue by asiekierka** [elytra/FruitPhone#21]
Minecraft 1.12.1, BTM's magical testing modpack

java.lang.NullPointerException: Ticking screen
    at net.minecraft.item.ItemEnchantedBook.func_150895_a(SourceFile:110)
    at com.elytradev.fruitphone.client.gui.ScreenConfigureGlasses.func_73876_c(ScreenConfigureGlasses.java:512)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1777)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:2￼

**Comment by exaskye** [comment]
wonderful

**Comment by modmuss50** [comment]
Can confirm: https://pastebin.com/sepw8TuC
